repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: black
      description: 'Black: The uncompromising python code formatter'
      language_version: python3
      require_serial: true
      types: [python]

